security:
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: $2a$12$F5Pw594GvbFhhzi6svq34OtxPAcxcnSXmAXn9uY8FhVgI4Zr4fa0u
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~

    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12

    access_control:
            # require ROLE_ADMIN for /admin*

            - { path: ^/login$,         roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin, roles: ROLE_ADMIN }

